services:
  - name: air auth service
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auth_db_whk7
          property: connectionString

databases:
  - name: auth-db
    plan: free
